Comment: |
  Use the ARCHITECTURE key to determine whether the Intel (amd64) or Apple Silicon (arm64) version
  of Docker for Mac is downloaded. Defaults to Intel if not overridden.
  eg "--key ARCHITECTURE=arm64"
Description: Downloads the latest version of Docker and creates a package.
Identifier: com.github.smithjw.pkg.Docker
ParentRecipe: com.github.smithjw.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  BUNDLE_ID: com.docker.docker

Process:
- Processor: PkgRootCreator
  Arguments:
    pkgdirs:
      Applications: '0775'
    pkgroot: '%RECIPE_CACHE_DIR%/%NAME%-%ARCHITECTURE%'

- Processor: Copier
  Arguments:
    destination_path: '%pkgroot%/Applications/Docker.app'
    source_path: '%pathname%/Docker.app'

- Processor: PkgCreator
  Arguments:
    pkg_request:
      chown:
      - group: admin
        path: Applications
        user: root
      id: '%BUNDLE_ID%.%ARCHITECTURE%'
      options: purge_ds_store
      pkgname: '%NAME%-%ARCHITECTURE%-%version%'
      scripts: scripts
