Comment: Created with Recipe Robot v2.2.0 (https://github.com/homebysix/recipe-robot)
Description: Downloads the latest version of Docker and imports it into Munki.
Identifier: com.github.autopkg-jby-recipes.munki.Docker
ParentRecipe: com.github.autopkg-jby-recipes.download.Docker
MinimumVersion: 1.0.0

Input:
  NAME: Docker
  MUNKI_REPO_SUBDIR: apps/%NAME%
  pkginfo:
    catalogs:
    - testing
    description: Spice up your Dock a little.
    developer: Docker Inc
    display_name: Docker
    name: '%NAME%'
    unattended_install: true

Process:
- Processor: MunkiImporter
  Arguments:
    pkg_path: '%pathname%'
    repo_subdirectory: '%MUNKI_REPO_SUBDIR%'
