---
Comment: |
  Use the ARCHITECTURE key to determine whether the Intel (amd64) or Apple Silicon (arm64) version
  of Docker for Mac is downloaded. Defaults to Intel if not overridden.
  eg "--key ARCHITECTURE=arm64"
Description: Downloads the latest version of Docker, packages it, then installs.
Identifier: com.github.smithjw.install.Docker
ParentRecipe: com.github.smithjw.pkg.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: amd64

Process:
  - Processor: Installer
