Description: Downloads the latest version of Docker and creates a package.
Identifier: com.github.smithjw.pkg.Docker
ParentRecipe: com.github.smithjw.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker

Process:
  - Processor: PkgRootCreator
    Arguments:
      pkgdirs: {}
      pkgroot: '%RECIPE_CACHE_DIR%/payload'

  - Processor: AppPkgCreator
    Arguments:
      app_path: '%pathname%/%NAME%.app'
      pkg_path: '%RECIPE_CACHE_DIR%/%NAME%-%ARCHITECTURE%-%version%.pkg'

  - Processor: com.github.smithjw.processors/FriendlyPathDeleter
    Arguments:
      fail_deleter_silently: True
      path_list:
        - '%RECIPE_CACHE_DIR%/payload'
